//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreFundacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int IDTelefono { get; set; }
        public int IDTutor { get; set; }
        public string Telefono1 { get; set; }
        public string Tipo { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
