//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;


namespace PreFundacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.Telefonos = new HashSet<Telefono>();
        }
    
        public int IDTutor { get; set; }
        [Required(ErrorMessage="Es de a ley")]
        public string CURP { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Actividad { get; set; }
        public string Domicilio { get; set; }
    
        public virtual ICollection<Telefono> Telefonos { get; set; }
    }
}
